import { useEffect, useState } from 'react';
import api from '../services/api';
import { Empty, Loading, Table, Toast } from '../components/UI';

const initialForm = { startDate: '', endDate: '', leaveType: 'Casual', reason: '', recipientEmail: '' };
export default function LeavePage({ user }) {
  const [leaves, setLeaves] = useState([]); const [approvers, setApprovers] = useState([]); const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const requests = [api.get('/leaves')]; if (user.role === 'faculty') requests.push(api.get('/leaves/approvers')); const [leaveResponse, approverResponse] = await Promise.all(requests); setLeaves(leaveResponse.data); setApprovers(approverResponse?.data || []); } catch (loadError) { setError(loadError.response?.data?.message || 'Could not load leave applications'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [user.role]);
  const submit = async (event) => { event.preventDefault(); setError(''); try { await api.post('/leaves', form); setForm(initialForm); setMessage('Leave application submitted'); load(); } catch (saveError) { setError(saveError.response?.data?.message || 'Could not submit leave application'); } };
  const review = async (id, status) => { const reviewComment = window.prompt(`${status} comment (optional):`, '') ?? ''; try { await api.patch(`/leaves/${id}/review`, { status, reviewComment }); setMessage(`Leave ${status.toLowerCase()}`); load(); } catch (reviewError) { setError(reviewError.response?.data?.message || 'Could not review leave'); } };
  const openEmail = (leave) => { const template = leave.emailTemplate; window.location.href = `mailto:${leave.recipientEmail || ''}?subject=${encodeURIComponent(template.subject)}&body=${encodeURIComponent(template.body)}`; };
  return <><div className="page-title"><div><span className="eyebrow">LEAVE WORKFLOW</span><h2>{user.role === 'faculty' ? 'Apply for leave' : 'Leave approvals'}</h2><p className="muted">{user.role === 'faculty' ? 'Submit an application and open the email draft for your approver.' : 'Review faculty leave applications.'}</p></div></div><Toast message={message || error} error={Boolean(error)} onClose={() => { setMessage(''); setError(''); }} />{user.role === 'faculty' && <section className="panel leave-form-panel"><form onSubmit={submit}><div className="attendance-filters"><label>Start date<input type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} required /></label><label>End date<input type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} required /></label><label>Leave type<select value={form.leaveType} onChange={(event) => setForm({ ...form, leaveType: event.target.value })}><option>Casual</option><option>Medical</option><option>Emergency</option><option>Other</option></select></label><label>Send to<select value={form.recipientEmail} onChange={(event) => setForm({ ...form, recipientEmail: event.target.value })} required><option value="">Select Admin/HOD</option>{approvers.map((item) => <option value={item.email} key={item._id}>{item.name} ({item.role})</option>)}</select></label></div><label>Reason<textarea value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} rows="4" required /></label><button className="primary-button" type="submit"><i className="bi bi-send" /> Submit application</button></form></section>}{loading ? <Loading /> : leaves.length ? <section className="panel"><Table headers={user.role === 'faculty' ? ['Dates', 'Type', 'Reason', 'Status', 'Email'] : ['Faculty', 'Dates', 'Type', 'Reason', 'Status', 'Actions']}>{leaves.map((leave) => <tr key={leave._id}><td>{new Date(leave.startDate).toLocaleDateString('en-IN')} - {new Date(leave.endDate).toLocaleDateString('en-IN')}</td>{user.role !== 'faculty' && <td>{leave.applicantId?.name}</td>}<td>{leave.leaveType}</td><td>{leave.reason}</td><td>{leave.status}</td>{user.role === 'faculty' ? <td><button className="secondary-button" type="button" onClick={() => openEmail(leave)}><i className="bi bi-envelope" /> Email draft</button></td> : <td>{leave.status === 'Pending' && <><button className="table-action" onClick={() => review(leave._id, 'Approved')} aria-label="Approve leave"><i className="bi bi-check-lg" /></button><button className="table-action danger" onClick={() => review(leave._id, 'Rejected')} aria-label="Reject leave"><i className="bi bi-x-lg" /></button></>}</td>}</tr>)}</Table></section> : <section className="panel"><Empty text="No leave applications yet." /></section>}</>;
}
