import { useEffect, useState } from 'react';
import api from '../services/api';
import { Table, Loading, Empty } from '../components/UI';

export default function ReportsEnhanced() {
  const [rows, setRows] = useState([]); const [subjects, setSubjects] = useState([]); const [subjectId, setSubjectId] = useState(''); const [loading, setLoading] = useState(true); const [threshold, setThreshold] = useState(75); const [search, setSearch] = useState('');
  useEffect(() => { Promise.all([api.get('/reports/summary'), api.get('/subjects')]).then(([summary, subjectResponse]) => { setRows(summary.data); setSubjects(subjectResponse.data); }).finally(() => setLoading(false)); }, []);
  const filtered = rows.filter((row) => (!subjectId || row.subject?._id === subjectId) && `${row.student?.name} ${row.student?.crNo} ${row.subject?.name}`.toLowerCase().includes(search.toLowerCase()));
  const subjectStats = subjects.map((subject) => { const subjectRows = rows.filter((row) => row.subject?._id === subject._id); const totalPresent = subjectRows.reduce((sum, row) => sum + row.present, 0); const totalClasses = subjectRows.reduce((sum, row) => sum + row.totalClasses, 0); return { ...subject, students: subjectRows.length, average: totalClasses ? (totalPresent / totalClasses * 100).toFixed(2) : '0.00' }; }).filter((subject) => !subjectId || subject._id === subjectId);
  const exportRows = [['Student', 'CR No.', 'Subject', 'Total classes', 'Present', 'Absent', 'Attendance %'], ...filtered.map((row) => [row.student?.name, row.student?.crNo, row.subject?.name, row.totalClasses, row.present, row.absent, row.percentage])];
  const download = (content, name, type) => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); };
  const exportCsv = () => download(exportRows.map((row) => row.join(',')).join('\n'), 'attendance-report.csv', 'text/csv');
  const exportExcel = () => download(`<table>${exportRows.map((row) => `<tr>${row.map((cell) => `<td>${cell ?? ''}</td>`).join('')}</tr>`).join('')}</table>`, 'attendance-report.xls', 'application/vnd.ms-excel');
  return <><div className="page-title"><div><span className="eyebrow">INSIGHTS & EXPORTS</span><h2>Attendance reports</h2><p className="muted">Filter attendance by subject and monitor performance.</p></div><div className="export-actions"><button className="secondary-button" onClick={exportExcel}><i className="bi bi-file-earmark-spreadsheet" /> Excel</button><button className="secondary-button" onClick={() => window.print()}><i className="bi bi-file-earmark-pdf" /> PDF</button><button className="secondary-button" onClick={exportCsv}><i className="bi bi-download" /> CSV</button></div></div><div className="report-controls"><div className="report-filter-row"><div className="search-box"><i className="bi bi-search" /><input placeholder="Search student or subject" value={search} onChange={(event) => setSearch(event.target.value)} /></div><label className="subject-filter">Subject<select value={subjectId} onChange={(event) => setSubjectId(event.target.value)}><option value="">All subjects</option>{subjects.map((subject) => <option value={subject._id} key={subject._id}>{subject.code} · {subject.name}</option>)}</select></label></div><label className="threshold">Low attendance threshold <input type="number" value={threshold} onChange={(event) => setThreshold(event.target.value)} />%</label></div><div className="subject-summary-grid">{subjectStats.map((subject) => <button className={`subject-summary ${subjectId === subject._id ? 'selected' : ''}`} key={subject._id} onClick={() => setSubjectId(subjectId === subject._id ? '' : subject._id)}><span>{subject.code}</span><strong>{subject.average}%</strong><small>{subject.name} · {subject.students} students</small></button>)}</div><section className="panel"><div className="panel-head"><div><span className="eyebrow">STUDENT-WISE SUMMARY</span><h3>{subjectId ? 'Subject attendance' : 'Attendance health'}</h3></div><span className="record-count">{filtered.length} records</span></div>{loading ? <Loading /> : filtered.length ? <Table headers={['Student', 'Subject', 'Classes', 'Present', 'Absent', 'Attendance', 'Status']}>{filtered.map((row) => <tr key={`${row.student?._id}-${row.subject?._id}`}><td><strong>{row.student?.name}</strong><small>CR {row.student?.crNo}</small></td><td>{row.subject?.name}</td><td>{row.totalClasses}</td><td>{row.present}</td><td>{row.absent}</td><td><strong>{row.percentage.toFixed(2)}%</strong></td><td><span className={`status ${row.percentage < threshold ? 'low' : 'good'}`}>{row.percentage < threshold ? 'Low attendance' : 'Good standing'}</span></td></tr>)}</Table> : <Empty text="Reports will populate after attendance is recorded." />}</section></>;
}
